### ISSUE TITLE
Comma delimited string no longer valid with limits 1.2.0

### ISSUE THREAD

**Issue by aterrel** [alisaifee/flask-limiter#61] opened 2016-10-14 21:04 UTC
While doing a pip install with flask-limiter, my code broke with a Value Error "couldn't parse rate limit string '2000/month,30/second' pointing to line 41 of limits/utils.py. It looks like the limits library as of 1.2.0 no longer supports comma delimited strings for specifying strings. 

https://github.com/alisaifee/limits/commit/21eac8b0db00bf57239b9356a1db68cec83965fa#diff-f5a532274827e0166a372e733fef093eL40

I would suggest either pinning the version of limits to 1.1.1 in the setup.py or fixing documentation.

**Comment by alisaifee** [comment] 2016-10-19 23:39
Hi @aterrel thanks for the report. This is definitely not intended. I'll try to fix this in a dot release.

**Comment by hwdavidward** [comment] 2016-11-04 13:59
@aterrel I just ran into this same issue. It looks like the commit to improve rate limit parsing broke this. For now just update EXPR to the previous value.

EXPR = re.compile(
    r"\s*([0-9]+)\s*(/|\s*per\s*)\s*([0-9]+)*\s*(hour|minute|second|day|month|year)[s]*",
    re.IGNORECASE
)

Or if I understand the requirements correctly update EXPR to:

EXPR = re.compile(
    r"^{SINGLE}(:?,{SINGLE})*$".format(SINGLE=SINGLE_EXPR.pattern),
    re.IGNORECASE
)

I changed the ; to a , in the above.

**Comment by marians** [comment] 2016-11-08 14:03
I just ran into the same issue. Thanks @aterrel for reporting this here and tracking down the root cause! Pinning to `limits==1.1.1` in our `requirements.txt` did the job for me.

**Comment by alisaifee** [comment] 2017-01-01 23:34
Sorry about the massive delay. This should be fixed in [limit 1.2.1](http://limits.readthedocs.io/en/stable/changelog.html#id1)

**Closed by alisaifee** 2017-01-01 23:34 UTC
