### ISSUE TITLE
Cannot integrate with Flask-Application builder as viewfunc(endpoint) != "{obj.__module__}.{obj.__name__}"

### ISSUE THREAD

**Issue by bolkedebruin** [alisaifee/flask-limiter#377] opened 2022-12-21 12:04 UTC
I am trying to add support for rate limiting in Flask-Application-Builder (FAB). This means that the limiter is instantiated as part of appbuilder initalizing and will be maintained in `app.appbuilder.sm.limiter` (sm is the security manager of FAB). 

FAB has several ways to provide logins. I tried decorating the login views as follows
```
class AuthDBView(AuthView):
    login_template = "appbuilder/general/security/login_db.html"

    @expose("/login/", methods=["GET", "POST"])
    def login(self):
        @self.appbuilder.sm.limiter.limit(limit_value="2 per 5 seconds")
        def _login(self):
            if g.user is not None and g.user.is_authenticated:
                return redirect(self.appbuilder.get_url_for_index)
            form = LoginForm_db()
            if form.validate_on_submit():
                user = self.appbuilder.sm.auth_user_db(
                    form.username.data, form.password.data
                )
                if not user:
                    flash(as_unicode(self.invalid_login_message), "warning")
                    return redirect(self.appbuilder.get_url_for_login)
                login_user(user, remember=False)
                next_url = request.args.get("next", "")
                return redirect(get_safe_redirect(next_url))
            return self.render_template(
                self.login_template, title=self.title, form=form, appbuilder=self.appbuilder
            )

        return _login(self)
```

This doesn't work.  This is due to:

`name = f"{obj.__module__}.{obj.__name__}"` evaluates to name being `AuthDBView.login` and in `view_func = app.view_functions.get(endpoint, None)` evaluates to `flask_appbuilder.security.views.login` (after `__module__.__name__`). This prevents lookups from working.

If I set `name = endpoint` in `route_limits` and do `marked_for_limiting = name in self._marked_for_limiting or endpoint in self._marked_for_limiting` things start working. 

I can provide a PR for this, but I am not sure of this is the right approach :-)

**Comment by alisaifee** [comment] 2022-12-21 17:22
I unfortunately have not used flask app builder before and might not have enough time to look into it in detail. If you can provide a very minimal example or test case to work off that would be appreciated.

**Comment by bolkedebruin** [comment] 2022-12-21 20:27
I'll try I think it has to do with the nested decorator inside a class.

**Comment by bolkedebruin** [comment] 2022-12-22 10:04
Believe me, I've tried :-). It's not possible as `self` is unavailable then. The pattern for FAB is no globals, so I can't have `limiter` somewhere for import.

**Comment by alisaifee** [comment] 2022-12-23 17:28
An alternate approach that might be worth looking at is to apply the rate limiting on the blueprint of `AuthDBView` (since all flask app builder views eventually end up as blueprints) instead of by decorating the route itself. 

This would have a few benefits:
- You wouldn't pay the cost of repeatedly creating an inner function on every request (and subsequently you wouldn't repeatedly decorate it)
- You can leave the view as is and control the rate limiting in the security manager (probably a better place to configure whether you want to rate limit or not?)

**Comment by alisaifee** [comment] 2022-12-23 17:39
@bolkedebruin here's a very basic demonstration of how you could go about integrating rate limiting into flask app builder: https://github.com/alisaifee/Flask-AppBuilder/commit/b2e969ac41e558099077ffc45005e41ef567cc5d

**Comment by alisaifee** [comment] 2022-12-24 19:14
Support for decorating non view functions has been added in [2.9.0](https://github.com/alisaifee/flask-limiter/releases/tag/2.9.0).

Additionally, this release allows using the object returned by `limiter.limit(...)` as a context manager so you could also get away without having an inner function and instead surrounding the code that you want to secure with a rate limit with the context manager ([here's](https://github.com/alisaifee/flask-limiter/blob/master/tests/test_context_manager.py#L10) an example).

All this comes with a strong disclaimer: both of the above approaches are not validated as extensively in the test suite as the regular route decoration or blueprint rate limiting approaches which have been around for years.  The actual requirement in this issue (to be able to add rate limiting to flask app builder's built in views) would in my opinion be best served simply by using the blueprint limiting functionality as I had shared earlier.

When you're able to validate if the issue is sufficiently resolved for you, please go ahead and close the issue!

**Comment by alisaifee** [comment] 2023-01-03 02:26
@bolkedebruin I'll go ahead and close this as there doesn't seem to be any more to do here.

**Closed by alisaifee** 2023-01-03 02:26 UTC

**Comment by bolkedebruin** [comment] 2023-01-09 11:14
Thank you indeed. I have used your code as inspiration for https://github.com/dpgaspar/Flask-AppBuilder/pull/1976
