### ISSUE TITLE
Requirements missing

### ISSUE THREAD

**Issue by AlmogCohen** [alisaifee/flask-limiter#35] opened 2015-08-27 07:09 UTC
I installed the package of version 0.8.1 using `pip install` and the package was unable to run since the `limits` package was missing. I just added manually the `limits` package to my requirements.

 Can you fix it please...

**Comment by alisaifee** [comment] 2015-08-27 16:30
Hi @AlmogCohen 

I just tested this by doing `pip install flask-limiter==0.8.1` in a fresh virtual env and `limits==1.0.8` was pulled in and installed as a dependency.

**Comment by AlmogCohen** [comment] 2015-08-27 16:35
Cool, I'll check it out soon again and notify you if there will be any
problem.

**Comment by alisaifee** [comment] 2015-09-16 04:20
Hi.  We're you able to confirm that the installation goes through?

**Comment by gcbirzan** [comment] 2015-09-16 07:51
The problem is that the egg on pypi is broken, it contains the limits package 'inline'.

**Comment by alisaifee** [comment] 2015-09-16 16:49
Hi @gcbirzan, thanks.  I'm not sure what you mean by inline? `limits` is specified in `setup.py`.

**Comment by gcbirzan** [comment] 2015-09-16 16:59
I mean it's in the egg file, just download it and see. There's a limits.py, and all the stuff from the limits package inside the flask-limiter directory.

**Comment by alisaifee** [comment] 2015-09-16 17:21
@gcbirzan : Ah, I see what you mean, good catch - I had a dirty build directory (I'll remove them for the next release). Having said that, those extra files are not in the install manifest and are therefore not installed in `site-packages` when the package is installed.

```
ls -1 lib/python2.7/site-packages/flask_limiter/*.py
lib/python2.7/site-packages/flask_limiter/__init__.py
lib/python2.7/site-packages/flask_limiter/_version.py
lib/python2.7/site-packages/flask_limiter/errors.py
lib/python2.7/site-packages/flask_limiter/extension.py
lib/python2.7/site-packages/flask_limiter/util.py
lib/python2.7/site-packages/flask_limiter/version.py
```

**Comment by gcbirzan** [comment] 2015-09-16 18:40
We're using buildout and it seems to install it. Also, any ETA on the next release?

**Comment by alisaifee** [comment] 2015-09-16 21:17
I've made a `0.8.2` release. No functional changes - just a cleaned up egg/tarball.

**Comment by gcbirzan** [comment] 2015-09-16 21:34
Much appreciated, I'll test it tomorrow morning (EU) and let you know!

**Comment by alisaifee** [comment] 2015-09-18 18:30
you're welcome. I'm going to close this specific issue for now as I don't see any problem with the dependency on `limits`

**Comment by alisaifee** [comment] 2015-10-05 11:40
Seems like there is indeed a problem when installing via tarball

**Comment by alisaifee** [comment] 2015-10-05 11:44
Fixed as per #38

**Closed by alisaifee** 2015-10-05 11:44 UTC
