### ISSUE TITLE
moving-window with deduct_when don't block

### ISSUE THREAD

**Issue by soufianechalouh** [alisaifee/flask-limiter#448] opened 2024-05-30 21:16 UTC
The limiter misbehaves in many ways when using `moving-window` strategy with `deduct_when` not `None`. In most situations, requests can be processed even though the limit is breached. I will highlight one clear example.

## Expected Behaviour

Requests should be blocked when the cost (or cost + previous consumption) exceeds the limit.

## Current Behaviour

Requests aren't blocked when the cost exceeds the limit. 

![image](https://github.com/alisaifee/flask-limiter/assets/32603792/730667c2-8b5a-42e0-8d3c-fcd2b982d15c)

## Steps to Reproduce

![image](https://github.com/alisaifee/flask-limiter/assets/32603792/c6e9724e-670a-4f25-abb3-d7538dce6777)

Using the example provided in [kitchensink.py](https://github.com/alisaifee/flask-limiter/blob/master/examples/kitchensink.py):

1. Setup strategy of Limiter as `moving-window`
2. Add a function to `deduct_when` keyword argument of the limiter (any function)
3. Set cost higher than limit
4. Run a request

## Your Environment

- Flask-limiter version: 3.7.0
- Flask version: 3.0.3
- Operating system: I tried both Windows11 and Ubuntu
- Python version: 3.9.9
- Redis: 4.x, 6.2, and 7.2.5 all failed

Note that if the limit is reached exactly, the limiter starts blocking. Example:

1. Set limit to 10
2. Set cost to 5
3. Run two queries (consuming the 10)
4. The third query fails.

When the limit is not reached, query goes through. Example:

1. Set limit to 10
2. Cost to 4
3. Two queries => Success. The query cost is saved in Redis. The total consumed is 8. Expected: Not enough cost left to run a third query
4. As many more queries => Query not stopped. The cost is not saved in Redis

Note: This only happens when `deduct_when` is not set to None. Any function passed through `deduct_when` creates the problem.

**Comment by alisaifee** [comment] 2024-06-04 14:39
@soufianechalouh thanks for reporting this. Acknowledging that this is a bug and I can reproduce it. 

The issue is actually in the implementation of the `moving-window` strategy in the [limits](https://github.com/alisaifee/limits) library (I haven't verified it but I don't think it would matter which `storage` option you use).

**Comment by soufianechalouh** [comment] 2024-06-06 19:13
Thanks @alisaifee. I believe `moving-window` requires Redis. I will look at the code and see if I can fix it.

**Comment by alisaifee** [comment] 2024-06-11 23:10
> Thanks @alisaifee. I believe `moving-window` requires Redis. I will look at the code and see if I can help fix it.

moving-window is implemented for redis, mongodb & in-memory.

After digging into it a bit the issue is two fold:
- in the moving window implementation if you try to perform a `hit` with a cost exceeding the available capacity, nothing is deducted. This is different from fixed window where an automic increment is performed and the returned value is checked against the capacity. This is why this scenario works for fixed window
- the `test` method doesn't take into account `cost` - therefore when the `test` is performed for conditional deduction, it succeeds since it only tests for whether the limit has already been exceeded for a unit `cost`.

**Comment by alisaifee** [comment] 2024-06-11 23:57
Maybe solution: https://github.com/alisaifee/limits/pull/220

**Comment by snaptravel-eng** [comment] 2024-06-21 04:15
Thank you @alisaifee were you able to help resolve this? Thank you

**Comment by alisaifee** [comment] 2024-07-21 01:55
Released in [3.8.0](https://github.com/alisaifee/flask-limiter/releases/tag/3.8.0)

**Closed by alisaifee** 2024-07-21 01:55 UTC
Labels: bug
