### ISSUE TITLE
Can't exempt nested blueprints

### ISSUE THREAD

**Issue by matthew-mcallister** [alisaifee/flask-limiter#326] opened 2022-04-05 02:36 UTC
The logic for exempting nested blueprints is wrong---whether exempting the parent blueprint or the child blueprint.

This example should work:
```python3
foo_bp = Blueprint('foo_bp', __name__)
bar_bp = Blueprint('bar_bp', __name__, url_prefix='/bar')
foo_bp.register_blueprint(bar_bp)
limiter.exempt(foo_bp)
limiter.exempt(bar_bp)
```

What happens is that `limiter._blueprints_exempt == ['foo_bp', 'bar_bp']`, but `request.blueprint == 'foo_bp.bar_bp'`, so the exemption doesn't apply.

I think the easiest solution would be to change the test to `limiter._blueprints_exempt.isdisjoint(set(request.blueprint.split('.')))`. This would automatically exempt all children of a parent blueprint, which I think seems the most obvious behavior.

**Comment by alisaifee** [comment] 2022-04-06 01:38
Thanks for the report. I can't actually remember if I knew that blueprints can be nested 😁

**Comment by alisaifee** [comment] 2022-04-06 03:41
I have something working (turned out nested blueprints were not just being ignored for exemptions, but also not working in the case of having an explicit limit registered on a blueprint which gets nested under another blueprint).

Since this behaviour has been around .. forever, recursively exempting blueprints is implemented as an opt in and is not the default behaviour.

**Comment by alisaifee** [comment] 2022-04-08 03:26
I've pushed the implementation that fixes picking up exemptions for blueprints that are explicitly exempt to master which you can test out, or if you prefer to use a test build:
```
pip install -i https://test.pypi.org/simple/ Flask-Limiter==2.2.0.post0.dev23
```

The change includes adding the `flag` parameter to the `exempt` function which provides finer grained control over the scope of the exemption. More details [here](https://flask-limiter.readthedocs.io/en/latest/recipes.html#nested-blueprints)

I'll hold off from making an official release till tomorrow so that I can think through any regressions this may cause.

**Comment by alisaifee** [comment] 2022-04-11 23:00
Resolved in [2.3.0](https://flask-limiter.readthedocs.io/en/stable/changelog.html#v2-3-0)

**Closed by alisaifee** 2022-04-11 23:00 UTC

**Comment by alisaifee** [comment] 2022-04-19 01:57
Just a heads up @matthew-mcallister - I ended up making a crappy mistake in 2.3.0 where changing the api for `exempt` had an unfortunate side effect where the additional `flags` argument was incompatible with using `exempt` as a decorator for view functions. To address that I'll be making `flags` a keyword only argument in 2.4.+
