### ISSUE TITLE
version not recognized

### ISSUE THREAD

**Issue by slavkoja** [alisaifee/flask-limiter#80] opened 2017-08-12 08:39 UTC
Hi,

i am trying to build ebuild for Funtoo (Gentoo based) Linux with latest version (0.9.5.tar.gz) which (in short) simple uses ``setup.py`` , but i got warning:
```
...
running install_scripts
/usr/lib64/python3.5/site-packages/setuptools/dist.py:345: UserWarning: The version specified ('unknown') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
```
Then i did small script witch commands from ``setup.py`` and i enabled verbose for version check:
```python
versioneer.get_version(verbose=True)
```
It reports:
```
get_version():
no .git in /var/tmp/portage/dev-python/flask-limiter-0.9.5/work/flask-limiter-0.9.5
guessing rootdir is '/var/tmp/portage/dev-python/flask-limiter-0.9.5/work/flask-limiter-0.9.5', but 'flask-limiter-0.9.5' doesn't start with prefix 'flask_limiter-'
got version from default None
unknown
```
After i changed the ``versioneer.parentdir_prefix`` to ``"flask-limiter-"`` it works.

For now i don't know if there is mistake in ``parentdir_prefix`` or in Funtoo's install workflow, but i decided to report it - you will understand it better.

**Comment by alisaifee** [comment] 2017-08-17 01:46
Hi @slavkoja are you getting the tarball from github releases?

**Comment by slavkoja** [comment] 2017-08-17 09:50
yes, it was downloaded from https://github.com/alisaifee/flask-limiter/archive/0.9.5.tar.gz

**Comment by alisaifee** [comment] 2017-08-17 10:07
I think that might be the root cause - as the github tarballs aren't *release tarballs* in the sense that they don't have the version in the code. When I make a release on pypi - the tarball that is uploaded there has the version frozen in the code. If you were to get the tarball instead from https://pypi.python.org/pypi/Flask-Limiter#downloads - you would notice `python setup.py version` works fine.

**Comment by slavkoja** [comment] 2017-08-17 12:24
Sure, i tried this in ``virtualenv`` already and with ``pip`` it works, as you wrote. I didn't inspect why it works -- because it works ;-). But this doesn't touch the initial point of my report -- the ``parentdir_prefix`` value.

BTW, IMO both tarballs (releases here and on pypi) have to be identical, because they are two different places for the same release version only.

**Comment by alisaifee** [comment] 2017-08-18 01:44
Hi @slavkoja you're right about the `parentdir_prefix` being incorrect - though it turns out it isn't the root problem. Versioneer can handle github generated tarballs by hard coding the tag value into the `_version.py` file when `git archive` is run. I will create a fix for this and make a release soon.

**Comment by alisaifee** [comment] 2017-10-23 04:29
This should be already fixed. Please reopen if that is not the case.

**Closed by alisaifee** 2017-10-23 04:29 UTC
